name: sentistrength
services:
  backend:
    image: sentistrength:latest
    pull_policy: never
    ports:
      - "8848:8080"
    environment:
      - DB_ADDRESS=${DB_ADDRESS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${NJU_PASSWORD}
      - TRACKER_URL=${TRACKER_URL}
    restart: "on-failure"